#pragma config(Motor,  port1,           FDL,           tmotorVex393_HBridge, openLoop, driveLeft)
#pragma config(Motor,  port3,           Shoulder,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           Elbow,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           Wrist,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          FDR,           tmotorVex393_HBridge, openLoop, reversed, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  /* Set bStopTasksBetweenModes to false if you want to keep user created tasks
  	 running between Autonomous and Driver controlled modes. You will need to
  	 manage all user created tasks if set to false. */
  bStopTasksBetweenModes = true;

	/* Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
		 used by the competition include file, for example, you might want
		 to display your team name on the LCD in this function.
		 bDisplayCompetitionStatusOnLcd = false;

  All activities that occur before the competition starts
  Example: clearing encoders, setting servo positions, ... */
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
  motor[FDL] = 127; //Drive forward from start
  motor[FDR] = 127;
  wait1Msec(1000);

	motor[FDL] = 0;
	motor[FDR] = 0;
	wait1Msec(100);

	motor[FDL] = -127; //Reverse a bit to get away from cone
	motor[FDR] = -127;
	wait1Msec(500);

	motor[FDL] = 0;
	motor[FDR] = 0;
	wait1Msec(100);

	motor[FDL] = 127; //Turn a bit to right to align with cone
	motor[FDR] = -127;
	wait1Msec(200);

	motor[FDL] = 0;
	motor[FDR] = 0;
	wait1Msec(100);

	motor[Elbow] = 127; //Deploy arm at elbow to grab cone
	wait1Msec(350);

	motor[Elbow] = 0;
	wait1Msec(100);

	motor[Wrist] = 127; //Open claw to accept cone
	wait1Msec(100);

	motor[Wrist] = 0;
	wait1Msec(100);

	motor[FDL] = 127; //Drive forward to center cone loop into claw
	motor[FDR] = 127;
	wait1Msec(100);

	motor[FDL] = 0;
	motor[FDR] = 0;
	wait1Msec(100);

	motor[Wrist] = -127; //Close claw around cone loop
	wait1Msec(100);

	motor[Wrist] = 0;
	wait1Msec(100);

	motor[FDL] = -127; //Turn left towards tower
	motor[FDR] = 127;
	wait1Msec(250);

	motor[FDR] = 0;
	motor[FDL] = 0;
	wait1Msec(100);

	motor[Elbow] = -127; //Raise Arm at shoulder to get cone off the ground
	wait1Msec(200);

	motor[Elbow] = 0;
	wait1Msec(100);

	motor[FDL] = 127; //Drive forward towards tower
	motor[FDR] = 127;
	wait1Msec(150);

	motor[FDL] = 0;
	motor[FDR] = 0;
	wait1Msec(100);

	motor[Elbow] = -127; //Lower elbow a bit to make sure cone can land on tower
	wait1Msec(200);

	motor[Elbow] = 0;
	wait1Msec(100);

	motor[Wrist] = 127; //Open claw, releasing cone onto fixed team stand
	wait1Msec(100);

	motor[Wrist] = 0;
	wait1Msec(100);

	motor[FDL] = -127; //Reverse away from stand
	motor[FDR] = -127;
	wait1Msec(200);

	motor[FDL] = 0;
	motor[FDR] = 0;
	wait1Msec(100);
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
  while (true)
  {
  	motor[FDL] = vexRT[Ch3];
  	motor[FDR] = vexRT[Ch2];


  	if (vexRT[Btn6U] == 1) //Shoulder motor
  	{
  		motor[Shoulder] = 127;
  	}
  	else if (vexRT[Btn6D] == 1)
  	{
  		motor[Shoulder] = -127;
    }
    else
    {
    	motor[Shoulder] = 0;
    }


    if (vexRT[Btn5U] == 1) //Elbow motor
    {
    	motor[Elbow] = 127;
    }
    else if (vexRT[Btn5D] == 1)
    {
    	motor[Elbow] = -127;
    }
    else
    {
    	motor[Elbow] = 0;
    }


    if (vexRT[Btn8L] == 1) //Wrist motor
    {
    	motor[Wrist] = 127;
    }
    else if (vexRT[Btn8R] == 1)
    {
    	motor[Wrist] = -127;
    }
    else
    {
    	motor[Wrist] = 0;
  	}
  }
}
