#pragma config(Motor,  port1,           FDL,           tmotorVex393_HBridge, openLoop, driveLeft)
#pragma config(Motor,  port2,           FDL2,          tmotorVex393_MC29, openLoop, reversed, driveLeft)
#pragma config(Motor,  port3,           LLT,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           LLB,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           RLT,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           RLB,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           Claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           FDR2,          tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port10,          FDR,           tmotorVex393_HBridge, openLoop, reversed, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

void pre_auton()
{
	bStopTasksBetweenModes = true;
}

task autonomous()
{
	motor[FDL] = 127; //drive forward
	motor[FDL2] = 127;
	motor[FDR] = 127;
	motor[FDR2] = 127;
	wait1Msec(2500);

	motor[FDL] = 0; //stop
	motor[FDL2] = 0;
	motor[FDR] = 0;
	motor[FDR2] = 0;
	wait1Msec(2500);

	motor[LLT] = 127; //raise claw
	motor[LLB] = 127;
	motor[RLT] = 127;
	motor[RLB] = 127;
	wait1Msec(10000);

	motor[LLT] = 0; //Stop lift
	motor[LLB] = 0;
	motor[RLT] = 0;
	motor[RLB] = 0;
	wait1Msec(1000);

	motor[Claw] = -127; //open claw
	wait1Msec(2500);

	motor[Claw] = 0;
	wait1Msec(2500);

}

task usercontrol()
{
	while (true)
	{
		motor[FDL] = vexRT[Ch3];
		motor[FDL2] = vexRT[Ch3];

		motor[FDR] = vexRT[Ch2];
		motor[FDR2] = vexRT[Ch2];

		if(vexRT[Btn5U] == 1)
		{
			motor[LLT] = 127;
			motor[LLB] = 127;
			motor[RLT] = 127;
			motor[RLB] = 127;
		}

		else if(vexRT[Btn5D] == 1)
		{
			motor[LLT] = -127;
			motor[LLB] = -127;
			motor[RLT] = -127;
			motor[RLB] = -127;
		}

		else
		{
			motor[LLT] = 0;
			motor[LLB] = 0;
			motor[RLT] = 0;
			motor[RLB] = 0;
		}

		if(vexRT[Btn6U] == 1)
		{
			motor[Claw] = 127;
		}

		else if(vexRT[Btn6D] == 1)
		{
			motor[Claw] = -127;
		}

		else
		{
			motor[Claw] = 0;
		}
	}
}
